import type { GlossResult } from "./types.ts";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Render the attribution line, e.g. "@handle · Jun 20, 2026". */
export function formatAttribution(result: GlossResult): string {
  const { handle, date } = result.attribution;
  return [handle, date].filter((part): part is string => Boolean(part && part.trim())).join(" · ");
}

/**
 * Build a standalone, self-contained HTML document for the print sheet — a
 * single letter page, summary-first, no app chrome. Pure and dependency-free so
 * it can be unit tested and opened via a blob URL.
 */
export function buildPrintHtml(result: GlossResult): string {
  const attribution = formatAttribution(result);

  const keyPoints = result.keyPoints
    .map((point) => `<li>${escapeHtml(point)}</li>`)
    .join("\n          ");

  const related = result.relatedReads.length
    ? `
      <section class="related">
        <div class="label">Related reading</div>
        <ul class="reads">${result.relatedReads
          .map(
            (read) => `
          <li><span class="read-book">${escapeHtml(read.title)}</span> <span class="read-author">— ${escapeHtml(
            read.author,
          )}</span><span class="read-why"> · ${escapeHtml(read.why)}</span></li>`,
          )
          .join("")}
        </ul>
      </section>`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Gloss — print sheet</title>
  <style>
    :root { color-scheme: light; }
    * { box-sizing: border-box; }
    html, body { margin: 0; padding: 0; background: #fff; color: #1a1a1a; }
    body {
      font-family: Georgia, "Times New Roman", serif;
      line-height: 1.45;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .sheet { max-width: 7in; margin: 0 auto; padding: 0.8in 0.75in; }
    .masthead {
      display: flex; align-items: baseline; justify-content: space-between;
      border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; margin-bottom: 22px;
    }
    .wordmark { font-size: 22px; font-weight: 700; letter-spacing: -0.01em; }
    .wordmark-sub { font-size: 11px; color: #6b6b6b; font-style: italic; }
    .label {
      font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
      font-size: 10px; font-weight: 600; letter-spacing: 0.12em;
      text-transform: uppercase; color: #8a8a8a; margin-bottom: 8px;
    }
    .tldr { font-size: 20px; line-height: 1.4; font-weight: 700; margin: 0 0 6px; }
    .attribution {
      font-size: 12px; color: #6b6b6b; font-style: italic; margin: 0 0 22px;
    }
    .points { margin: 0 0 24px; padding-left: 1.1em; }
    .points li { font-size: 14.5px; line-height: 1.5; margin-bottom: 8px; }
    .related { border-top: 0.5px solid #d8d8d8; padding-top: 14px; }
    ul.reads { list-style: none; margin: 0; padding: 0; }
    ul.reads li { font-size: 12.5px; line-height: 1.5; margin-bottom: 5px; }
    .read-book { font-weight: 700; }
    .read-author { color: #6b6b6b; }
    .read-why { color: #4a4a4a; font-style: italic; }
    footer {
      margin-top: 28px; padding-top: 10px; border-top: 0.5px solid #d8d8d8;
      font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
      font-size: 10px; color: #a0a0a0; text-align: center;
    }
    @page { size: letter; margin: 0; }
  </style>
</head>
<body>
  <main class="sheet">
    <div class="masthead">
      <span class="wordmark">Gloss</span>
      <span class="wordmark-sub">a page worth printing</span>
    </div>

    <div class="label">Summary</div>
    <p class="tldr">${escapeHtml(result.tldr)}</p>
    ${attribution ? `<p class="attribution">${escapeHtml(attribution)}</p>` : ""}

    <ul class="points">
          ${keyPoints}
    </ul>
${related}
    <footer>Generated by Gloss · gloss.so</footer>
  </main>
</body>
</html>`;
}
